project:
  type: book

book:
  title: "R Programming"
  author: "Qi"
  date: "2024/1/11"
  chapters:
    - index.qmd
    - intro.qmd
    - part: tidyverse.qmd
      chapters: 
        - dplyr.qmd
        - stringr.qmd

bibliography: references.bib

format:
  html:
    theme: custom.scss

editor: visual

